'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("monZi.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  monZi(먼지) - PC 미세먼지 실시간 조회 &amp; 알림 프로그램
        '''개발: 박동준 | PBJSoftware
        '''프로젝트 시작: 20180622 | 최종 빌드: 20190801
        '''
        '''※ monZi는 AirKorea(한국환경공단 에어코리아)로부터 대기오염정보, 측정소정보를 제공받고 있습니다. 해당 데이터는 실시간 관측된 자료이기 때문에 오류가 있을 수 있으며, 표출방식에 따라 값이 다를 수 있습니다. 또한 측정소 현지 사정이나 데이터의 수신상태에 따라 미수신될 수 있습니다. ※
        '''
        '''본 프로그램(monZi) 는 PBJ소프트웨어에서 개발하고 배포하는 무료 소프트웨어입니다.
        '''이 프로그램은 개인, 가정, 기업, 관공서, 학교, 학원 등 언제나 어디에서나 무료로 제약없이 사용 가능합니다.
        '''본 프로그램은 현재 개발중이므로 일부 기능이나 작동 등에 결함이 있을 수 있습니다. 또한 본 프로그램으로 인해 생기는 사고나 불이익은 PBJ소프트웨어 측에서 책임 져 드릴 수 없으니 참고 바랍니다.
        '''이 프로그램을 배포하실 수는[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property appinfo() As String
            Get
                Return ResourceManager.GetString("appinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property closeicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property closeicon_b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeicon_b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_2_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_2_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_3_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_3_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_4_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_4_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_5_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_5_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_6_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_6_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_7_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_7_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property dash_maintenance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dash_maintenance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property hideicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hideicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property hisicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hisicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_er() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_er", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr6() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr6", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr7() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr7", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_gr8() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_gr8", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ico_load() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_load", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property info_blog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_blog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property info_gmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_gmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property info_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property info_tg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_tg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property info_yt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_yt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property infoban() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infoban", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property listicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property locicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property lockicon_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockicon_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property lockicon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockicon_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property menu_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property menu_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property menu_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property menu_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property monZi() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("monZi", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property moreicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moreicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property noticetxt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noticetxt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property opticon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("opticon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property popup_snd() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("popup_snd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property refreshico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refreshico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property shadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property stationicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stationicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;response&gt;
        '''  &lt;header&gt;
        '''    &lt;resultCode&gt;00&lt;/resultCode&gt;
        '''    &lt;resultMsg&gt;NORMAL SERVICE.&lt;/resultMsg&gt;
        '''  &lt;/header&gt;
        '''  &lt;body&gt;
        '''    &lt;items&gt;
        '''      &lt;item&gt;
        '''        &lt;stationName&gt;창전동&lt;/stationName&gt;
        '''        &lt;addr&gt;경기 이천시 창전동105-3&lt;/addr&gt;
        '''        &lt;tm&gt;8.6&lt;/tm&gt;
        '''      &lt;/item&gt;
        '''      &lt;item&gt;
        '''        &lt;stationName&gt;설성면&lt;/stationName&gt;
        '''        &lt;addr&gt;경기 이천시 설성면 신필리산 88-5(전파연구소 입구)&lt;/addr&gt;
        '''        &lt;tm&gt;9.3&lt;/tm&gt;
        '''      &lt;/item&gt;
        '''      &lt;item&gt;
        '''        &lt;stationName&gt;여주읍&lt;/stationName&gt;
        '''        &lt;addr&gt;경기 여주군 여주읍 하리131-11(여주군청 별관 2층 옥상)[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property testdata() As String
            Get
                Return ResourceManager.GetString("testdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property widget_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("widget_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property widget_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("widget_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
